id: P332D7206
initial_creation_type: input
source_metadata:
  title: Tsele Natsok Rangdrol Series
  language: bo
  description: 'Texts by Tsele Natsok Rangdrol (rtse le sna tshogs rang grol, b. 1608):'
  volume:
    b7d31a6776d24011b8086940728b1632:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Commentaries
created_at: '2022-03-01T01:55:10.312462'
last_modified_at: '2022-03-01T01:55:10.312465'
statistics:
  total_words: 1446
  total_non_words: 135
quality:
  non_words_ratio: 0.09
